### ISSUE TITLE
Default import configuration breaking sentences

### ISSUE THREAD

**Issue by negiiiii** [xulihang/BasicCAT#57]
It seems like the default import configuration isn't designed with Japanese text translation (especially those with extensive use of punctuations) in mind, therefore pretty much all sentences in the document I'm trying to translate were broken up in a quite undesirable fashion.
![Screenshot 2024-01-03 174651](https://github.com/xulihang/BasicCAT/assets/74807061/3a6bcadd-a114-4d28-90a1-d94109c64e49)
While it's possible to manually merge segments, in this specific case I would have to merge every segment of character speech myself which is a massive hassle. This could be prevented if there's an option to keep all the sentences the way they are in the source file, as they were already properly organized.
I would appreciate if this problem could be looked into asap.

**Comment by xulihang** [comment]
BasicCAT uses SRX for configuring the sentence segmentation.

You can use Ratel from [Okapi Framework](https://okapiframework.org/) to edit the rules.

The rule file lies in the project's config folder and its name is `segmentationRules.srx`.

Use Ratel to edit the rule file and delete `…` in the last rule so that it will not break at the position of `…`.

![image](https://github.com/xulihang/BasicCAT/assets/5462205/b6c857a0-28b0-4d54-8be0-799cf266a57d)


You can also disable sentence-level segmentation in the project settings if it meets your needs.

![image](https://github.com/xulihang/BasicCAT/assets/5462205/608b08ad-1f47-424d-9de7-cf64a2a97e47)

**Comment by negiiiii** [comment]
Thank you very much for the help.
